[package]
name = "command"
version = "0.1.0"
authors = ["Lainera <fistlain@hotmail.com>"]
edition = "2018"

[features]
default = []
std-write = []
rbf-write = ["ring_buffer"]

[dependencies]
ring_buffer = { git = "https://github.com/lainera/ring_buffer", optional = true }


